# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# Accelerate inferencing in heaviest components to improve performance
# by overriding their subchart values

image:
  repository: opea/chatqna-without-rerank
  tag: "1.2_fix_telemetry"
port: 8888
service:
  type: NodePort
  port: 8888
  nodePort: 30888

teirerank:
  enabled: false

vllm:
  image:
    repository: opea/vllm
    tag: 1.2
  extraCmdArgs: [
    "--tensor-parallel-size", "1",
    "--block-size", "128",
    "--max-num-seqs", "256",
    "--max-seq_len-to-capture", "2048"
  ]

# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0





# Override values in specific subcharts
tgi:
  LLM_MODEL_ID: Intel/neural-chat-7b-v3-3
  MAX_BATCH_SIZE: "1"
  MAX_INPUT_LENGTH: "2500"
  MAX_TOTAL_TOKENS: "4096"
  enabled: false
# disable guardrails-usvc by default
# See guardrails-values.yaml for guardrail related options
guardrails-usvc:
  enabled: false

# If you would like to switch to traditional UI image
# Uncomment the following lines
chatqna-ui:
  image:
    repository: "opea/chatqna-ui"
    tag: "${IMGVER}"
tei:
  resources:
    limits:
      habana.ai/gaudi: 0
  evenly_distributed: True

data-prep:
  image:
    tag: "${IMGVER}"
  # port: 6010
  # evenly_distributed: True
  # livenessProbe:
  #   httpGet:
  #     path: v1/health_check
  #     port: data-prep
  #   initialDelaySeconds: 5
  #   periodSeconds: 5
  #   failureThreshold: 2400

retriever-usvc:
  image:
    tag: "${IMGVER}"
  port: 7000
  evenly_distributed: True
embedding-usvc:
  image:
    repository: opea/embedding-tei
    tag: "${IMGVER}"
  evenly_distributed: True
  enabled: false
llm-uservice:
  image:
    repository: opea/llm-tgi
    tag: "1.0_fix"
  LLM_MODEL_ID: Intel/neural-chat-7b-v3-3
  evenly_distributed: True
  enabled: false


global:
  http_proxy: "http://proxy-dmz.intel.com:912"
  https_proxy: "http://proxy-dmz.intel.com:912"
  no_proxy: "corp.intel.com,.sh.intel.com,.bj.intel.com,localhost,127.0.0.1/8,10.239.241.94/24,10.112.228.130,10.112.228.122,10.233.0.0/18,10.233.64.0/18,chatqna,chatqna-chatqna-ui,chatqna-data-prep,chatqna-nginx,chatqna-vllm,chatqna-redis-vector-db,chatqna-retriever-usvc,chatqna-tei"
  HUGGINGFACEHUB_API_TOKEN: ""
  # set modelUseHostPath or modelUsePVC to use model cache.
  modelUseHostPath: ${MODELDIR}
  # modelUseHostPath: /mnt/opea-models
  # modelUsePVC: model-volume

  # Install Prometheus serviceMonitors for service components
  monitoring: false

  # Prometheus Helm install release name needed for serviceMonitors
  prometheusRelease: prometheus-stack
  HF_ENDPOINT: "http://hf-mirror.com"
